config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :invoices
  resources :services
  resources :products
  resources :clients

  root :to => redirect('/invoices')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :client
  has_many :line_items
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :invoice
  belongs_to :product, :optional => true
  belongs_to :service, :optional => true

  validate :must_be_product_or_service

  def must_be_product_or_service
    if product.blank? && service.blank?
      errors.add(:base, "A line item must be either a product or a service")
    elsif product.present? && service.present?
      errors.add(:base, "A line item can't be both a product and a service")
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  def index
    @clients = Client.all
  end

  # GET /clients/1
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: 'Client was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params)
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: 'Client was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def client_params
      params.require(:client).permit(:name, :email)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  after_action :save_line_items, except: [:index]

  def index
    @invoices = Invoice.all
  end

  def show
    @client = @invoice.client

    @line_items = (
      @invoice.line_items.joins(:product).where('products.price_cents != 0') +
      @invoice.line_items.joins(:service).where('services.price_cents != 0')
    ).group_by { |line_item| line_item.service.present? ? :service : :product }

    @total = @line_items.values.flatten.map { |line_item|
      [line_item.price_override_cents ||
       line_item&.product&.price_cents ||
       line_item&.service&.price_cents, line_item.quantity]
    }.sum { |(price_cents, quantity)|
      price_cents * quantity
    }
  end

  def new
    @invoice = Invoice.new
  end

  def edit
  end

  def create
    @invoice = Invoice.new(invoice_params)

    if @invoice.save
      redirect_to @invoice, notice: 'Invoice was successfully created.'
    else
      render :new
    end
  end

  def update
    if @invoice.update(invoice_params)
      redirect_to @invoice, notice: 'Invoice was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @invoice.destroy
    redirect_to invoices_url, notice: 'Invoice was successfully destroyed.'
  end

  private
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def save_line_items
      return if @invoice.blank?
      @invoice.line_items.each(&:save)
    end

    def invoice_params
      params.require(:invoice).permit(:client_id, :net_days, :note)
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  def create
    @line_item = LineItem.new(line_item_params)

    if @line_item.save
      redirect_to @line_item, notice: 'Line item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /line_items/1
  def update
    if @line_item.update(line_item_params)
      redirect_to @line_item, notice: 'Line item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /line_items/1
  def destroy
    @line_item.destroy
    redirect_to line_items_url, notice: 'Line item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def line_item_params
      params.require(:line_item).permit(:invoice_id, :product_id, :service_id, :price_override_cents, :quantity, :description)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      params.require(:product).permit(:name, :price_cents)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  def index
    @services = Service.all
  end

  # GET /services/1
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service, notice: 'Service was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /services/1
  def update
    if @service.update(service_params)
      redirect_to @service, notice: 'Service was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /services/1
  def destroy
    @service.destroy
    redirect_to services_url, notice: 'Service was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def service_params
      params.require(:service).permit(:name, :price_cents)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def to_money(cents)
    "$#{cents.to_s.insert(-3, ".")}"
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :client_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :client_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.email %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.collection_select :client_id, Client.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :net_days %>
    <%= form.number_field :net_days, id: :invoice_net_days %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note, id: :invoice_note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Net days</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.client.name %></td>
        <td><%= invoice.net_days %></td>
        <td><%= invoice.note %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<div id="summary">
  <p><strong>Client:</strong> <%= @client.name %></p>
  <p><strong>Attn:</strong> <%= @client.email %></p>
  <p><strong>Due Date:</strong> <%= @invoice.created_at.to_date + @invoice.net_days %></p>
  <p><strong>Notes:</strong> <%= @invoice.note %></p>
</div>

<table id="line_items">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Unit Price</th>
      <th>Quantity</th>
      <th>Subtotal</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan=5><strong>Products</strong></td>
    </tr>
    <% @line_items[:product].each do |line_item| %>
      <tr>
        <td><%= line_item.product.name %></td>
        <td><%= line_item.description %></td>
        <td><%= to_money(line_item.price_override_cents || line_item.product.price_cents) %></td>
        <td><%= line_item.quantity %></td>
        <td><%= to_money((line_item.price_override_cents || line_item.product.price_cents) * line_item.quantity) %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan=5><strong>Services</strong></td>
    </tr>
    <% @line_items[:service].each do |line_item| %>
      <tr>
        <td><%= line_item.service.name %></td>
        <td><%= line_item.description %></td>
        <td><%= to_money(line_item.price_override_cents || line_item.service.price_cents) %></td>
        <td><%= line_item.quantity %></td>
        <td><%= to_money((line_item.price_override_cents || line_item.service.price_cents) * line_item.quantity) %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th colspan=3>&nbsp;</th>
      <th>Total</th>
      <td><%= to_money(@total) %></td>
    </tr>
  </tfoot>
</table>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AccountsReceivable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <ul>
          <li><%= link_to "Clients", clients_path %></li>
          <li><%= link_to "Products", products_path %></li>
          <li><%= link_to "Services", services_path %></li>
          <li><%= link_to "Invoices", invoices_path %></li>
          <li><%= link_to "Line Items", line_items_path %></li>
        </ul>
      </nav>
      <div class="main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :invoice_id %>
    <%= form.collection_select :invoice_id, Invoice.all, :id, :id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.collection_select :product_id, Product.all, :id, :name, :include_blank => true %>
  </div>

  <div class="field">
    <%= form.label :service_id %>
    <%= form.collection_select :service_id, Service.all, :id, :name, :include_blank => true %>
  </div>

  <div class="field">
    <%= form.label :price_override_cents %>
    <%= form.number_field :price_override_cents, id: :line_item_price_override_cents %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :line_item_quantity %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :line_item_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Invoice</th>
      <th>Product</th>
      <th>Service</th>
      <th>Price override cents</th>
      <th>Quantity</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.invoice.id %></td>
        <td><%= line_item.product&.name %></td>
        <td><%= line_item.service&.name %></td>
        <td><%= line_item.price_override_cents %></td>
        <td><%= line_item.quantity %></td>
        <td><%= line_item.description %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Invoice:</strong>
  <%= @line_item.invoice.id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product&.name %>
</p>

<p>
  <strong>Service:</strong>
  <%= @line_item.service&.name %>
</p>

<p>
  <strong>Price override cents:</strong>
  <%= @line_item.price_override_cents %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @line_item.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @line_item.description %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :price_cents %>
    <%= form.number_field :price_cents, id: :product_price_cents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price cents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price_cents %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price cents:</strong>
  <%= @product.price_cents %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :service_name %>
  </div>

  <div class="field">
    <%= form.label :price_cents %>
    <%= form.number_field :price_cents, id: :service_price_cents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price cents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.price_cents %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Price cents:</strong>
  <%= @service.price_cents %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>